name: CI to Docker Hub
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "10"
      - run: npm install
      - run: npm test
#  name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: <region>
#       -
#         name: Login to ECR
#         uses: docker/login-action@v1
#         with:
#           registry: <aws-account-number>.dkr.ecr.<region>.amazonaws.com
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          registry: docker.pkg.github.com
      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v1
      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./
      #     file: ./Dockerfile
      #     push: true
      #     tags: ushamandya/simplewhale:latest
      - name: build
        run: docker builder build -t 
      - name: Tags
        run: |
          docker tag back ${{ secrets.DOCKER_HUB_USERNAME }}/back:${{ github.sha }}
          docker tag back ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}/back:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/back:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}/back:latest
    # - name: Image digest
    #   run: echo ${{ steps.docker_build.outputs.digest }}
